name: GitHub Snake Animation 🐍

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Customized Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Kushagra-maker
          outputs: |
            dist/github-snake.svg?color_snake=#00FF00&color_dots=#000000
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00FF00
            dist/github-snake.gif?color_snake=#00FF00&color_dots=#000000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: 'Update customized snake animation [skip ci]'
