name: GitHub Snake Animation 🐍

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Customized Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Kushagra-maker
          outputs: |
            dist/github-snake.svg?color_snake=#fe9345&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#f775ff
            dist/github-snake.gif?color_snake=#fe9345&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: 'Update customized snake animation [skip ci]'
